language: node_js
os:
  - linux
  - osx
# Use latest stable node.js release
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
install:
  - npm install
  - npm prune
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run dist-macos; else npm run dist-linux; fi
# - npm test
